name: Eugene Johnson
description: Gene’s Blog
avatar: 
url: johnsonge.github.io
paginate: 5

rss-feed-limit: 10

footer-links:
  email: johnsonge@g.cofc.edu
  facebook: gene.johnson04
  github: johnsonge
  linkedin: johnsonge


# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

markdown: redcarpet
permalink: pretty
pygments: true