markdown: redcarpet
highlighter: pygments
permalink: /:title

url: http://johnsonge.github.io
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
# Site owner
owner:
  name: Eugene Johnson
  avatar: bio-photo.jpg
  bio: "Gene's Blog for 462"
  email: johnson.gene04@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: gene.johnson04
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: johnsonge
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: johnsonge
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]