# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Eugene Johnson"
description: > # this means to ignore newlines until "email:"
   A blog for CSCI 462

email: johnsonge@g.cofc.edu
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Eugene Johnson'
author: 'Eugene Johnson'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "johnsonge.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/johnsonge
    desc:	Connect with me on Linkedin
    share_url:
    share_title:
    share_link:



  - icon:	facebook
    url:	https://facebook.com/gene.johnson04
    desc: Find me on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/johnsonge
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
		
  - icon: linkedin
    url:
	desc:
	share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

